#!/bin/bash
mvn clean install
#cd target
#java -jar pimodbusmaster-0.0.1-SNAPSHOT.war
scp -P 2002 /home/denis/eclipse-workspace/pimodbusmaster/target/pimodbusmaster-0.0.1-SNAPSHOT.war pi@192.168.88.23:/usr/src/

